#!/usr/bin/env php
<?php

require_once __DIR__.'/GpKernel.php';

use Symfony\Framework\FoundationBundle\Console\Application;

$kernel = new GpKernel('dev', true);

$application = new Application($kernel);
$application->run();
