<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BundleUserBundleEntitiesUserProxy extends \Bundle\UserBundle\Entities\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setLogin($value)
    {
        $this->_load();
        return parent::setLogin($value);
    }

    public function getLogin()
    {
        $this->_load();
        return parent::getLogin();
    }

    public function setPassword($value)
    {
        $this->_load();
        return parent::setPassword($value);
    }

    public function getPassword()
    {
        $this->_load();
        return parent::getPassword();
    }

    public function setFirstName($value)
    {
        $this->_load();
        return parent::setFirstName($value);
    }

    public function getFirstName()
    {
        $this->_load();
        return parent::getFirstName();
    }

    public function setLastName($value)
    {
        $this->_load();
        return parent::setLastName($value);
    }

    public function getLastName()
    {
        $this->_load();
        return parent::getLastName();
    }

    public function setEmailAddress($value)
    {
        $this->_load();
        return parent::setEmailAddress($value);
    }

    public function getEmailAddress()
    {
        $this->_load();
        return parent::getEmailAddress();
    }

    public function getGender()
    {
        $this->_load();
        return parent::getGender();
    }

    public function setGender($gender)
    {
        $this->_load();
        return parent::setGender($gender);
    }

    public function getFullName()
    {
        $this->_load();
        return parent::getFullName();
    }

    public function addGroup($value)
    {
        $this->_load();
        return parent::addGroup($value);
    }

    public function getGroup()
    {
        $this->_load();
        return parent::getGroup();
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('id', 'login', 'password', 'firstName', 'lastName', 'emailAddress', 'group', 'gender');
    }
}